# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-07 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('compendium_nick_name', models.TextField()),
                ('biological_features_num', models.IntegerField(default=0)),
                ('sample_sets_num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalizeddata_id', models.BigIntegerField(default=1)),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compass_graphql.Module')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moduledata',
            unique_together=set([('module', 'normalizeddata_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('name', 'compendium_nick_name', 'user')]),
        ),
    ]
