version: '2'

services:
  nginx:
    build: ./nginx/
    ports:
      - "2424:80"
    volumes_from:
      - web
    links:
      - web:web
    networks:
      static-network:
        ipv4_address: 172.23.0.2

  postgres:
    image: postgres:latest
    volumes_from:
      - pg_data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - env
    expose:
      - "5433"
    ports:
      - "5433:5433"
    networks:
      static-network:
        ipv4_address: 172.23.0.3

  web:
    build: .
    env_file: env
    expose:
      - "80"
    links:
      - postgres:postgres
    volumes_from:
      - web_data
    volumes:
      - .:/app
    #command: gunicorn compass.wsgi:application -w 2 -b :8000
    tty: true
    networks:
      static-network:
        ipv4_address: 172.23.0.4

  pg_data:
    restart: always
    image: alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: "true"
    networks:
      static-network:
        ipv4_address: 172.23.0.11

  web_data:
    restart: always
    image: alpine
    volumes:
      - /app
    command: "true"
    networks:
      static-network:
        ipv4_address: 172.23.0.12

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
